[package]
name = "ebus"
version = "0.1.0"
authors = ["austin <austinstig@gmail.com>"]

[lib]
name="ebus"
path="src/lib.rs"

[[bin]]
name="ebus-bin"
path="src/bin.rs"

[build-dependencies]
bindgen="0.40.0"
cc = "1.0.25"
libc = "0.2.43"

[dependencies]
libc = "0.2.43"
num = "0.2.0"
